# -*- coding: utf-8 -*-
"""Tabiin Ghaozan Karim Pekan 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168IpIL5vzeCe0P_xA0r-9KUjVOW0pxBh
"""

print("Deskripsi Kendaraan")
list_kendaraan = ["motor", "transportasi darat", "250cc", "hitam", "2 roda"]
list_deskripsi = ["Rp. 7.000.000", "supra bapak"]
list_full_deskripsi = list_kendaraan + list_deskripsi
print(list_full_deskripsi)
list_kendaraan.insert(3, "yamahmud")
print(list_kendaraan)

print("Program Menentukan Bilangan Ganjil dan Genap")

bilangan = int(input("masukkan bilangan:"))

if bilangan%2==0:
  print("bilangan", bilangan, "adalah bilangan genap")
else:
  print("bilangan", bilangan, "adalah bilangan ganjil")

print("Selamat Datang di Program Hitung Luas Bangun Datar")
print("Mau itung apa nich?")
print("1. Persegi, 2 Segitiga, 3 Lingkaran")
luas_bangun_datar = input ("Mau itung apa?")
match luas_bangun_datar:
  case "1":
    print("persegi dong")
    sisi = int(input("masukan sisi"))
    hasil = sisi * sisi
    print("Luasnya", hasil)
  case "2":
    print("Segitiga dong")
    alas = int(input("masukkan alas"))
    tinggi = int(input("masukkan tinggi"))
    hasil = (0.5 * alas * tinggi)
    print("Luasnya", hasil)
  case "3":
    print("Lingkaran dong")
    jari = int(input("masukan jari-jari"))
    hasil = (3.14 * jari * jari)
    print("Luasnya", hasil)
  case _:
    print("salah pilih angka")